"use strict";
const myFriends = ['Jon', 'Sam', 'Alex'];
const newFriends = ['Zen', 'Neo', 'Tom'];
// const friendList: string[] = myFriends.push(...newFriends);
// console.log(friendList);
myFriends.push(...newFriends);
// console.log(myFriends);
// const friendList: string[] = [...myFriends, ...newFriends];
// console.log(friendList);
const greetingFriends = (...friendList) => friendList.forEach((name) => console.log(`Hi ${name}`));
greetingFriends('Bob', 'Don', 'Jon');
