"use strict";
// 04 - May - 2023
const dataA = [10, 20, 30];
const dataB = ['AA', 'BB', 'CC'];
const dataC = [true, false];
const dataD = [{ name: 'Sam' }, { name: 'Jon' }];
const dataE = [10, 20, 30];
const dataF = ['AA', 'BB', 'CC'];
const dataG = [true, false];
const dataH = [{ name: 'Sam' }, { name: 'Jon' }];
const dataI = [10, 20, 30];
const dataJ = ['AA', 'BB', 'CC'];
const dataK = [true, false];
const dataL = [{ name: 'Tom' }, { name: 'Don' }];
;
const dataM = ['Sam', 25];
const dataN = ['AA', true];
const dataO = [0, false];
const dataP = [{ name: 'Tom' }, 26];
console.log(dataM);
console.log(dataN);
console.log(dataO);
console.log(dataP);
